apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: naro
  labels:
    app: wordpress
spec:
  storageClassName: manual #Clase de almacenamiento -> volumen preexistente
  accessModes:
    - ReadWriteOnce #Permite que el volumen sea montado en modo lectura/escritura por un único nodo
  volumeMode: Filesystem #El volumen debe ser montado como un sistema de archivos
  resources: #Define los recursos solicitados
    requests: 
      storage: 8Gi
  volumeName: wordpress-pv #Nombre del volumen persistente al que esta reclamación se está vinculando
